# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Easter-Egg found ... (by MarkusTieger)

name: Auto Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    #outputs:
    #  upload_url: ${{ steps.create_release.outputs.upload_url }}
    #  release: ${{ steps.build.outputs.release }}
    #  commit: ${{ steps.commithash.outputs.sha_short }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Set outputs
        id: commithash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

          #- name: Generate build number
          #  id: buildnumber
          #  uses: einaregilsson/build-number@v3
          #  with:
          #    token: ${{ secrets.github_token }}



      - name: Set up JDK 17 (Linux)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'



      - name: Make gradlew executable
        run: chmod +x ./gradlew



      - name: Build with Gradle (Linux-Amd64)
        #run: ./gradlew build
        #working-directory: .
        id: build
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build "-Dos.name=Linux" "-Dos.arch=amd64" "-Dos.version=5.16.0-37" --refresh-dependencies
        env:
          build_number: ${{ github.run_number }}
          commit_hash: ${{ steps.commithash.outputs.sha_short }}
          gituser: ${{ github.actor }}
          gitpwd: ${{ secrets.GITHUB_TOKEN }}
          os-linux: true


      #- name: Upload Artifact (Linux)
      #  uses: actions/upload-artifact@v2.2.4
      #  with:
      #    name: tigxa-1.0.0-linux
      #    path: build/libs
      #  continue-on-error: true

      - name: Build Version-Info
        run: echo ${{ steps.build.outputs.release }} > version.txt && echo ${{ steps.build.outputs.build_number }} >> version.txt && echo ${{ steps.commithash.outputs.sha_short }} >> version.txt

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.build.outputs.release }}-${{ steps.build.outputs.build_number }}
          release_name: ${{ steps.build.outputs.release }}-${{ steps.build.outputs.build_number }}
          #body: |
          #  Changes in this Release
          #  - First Change
          #  - Second Change
          draft: false
          prerelease: false

      - name: Upload Version-Info
        id: upload-version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: version.txt
          asset_name: version.txt
          asset_content_type: application/java-archive
        continue-on-error: true

      - name: Upload Build Jar (Linux-Amd64)
        id: upload-build-jar-linux-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: build/libs/tigxa-${{ steps.build.outputs.release }}.jar
          asset_name: tigxa-${{ steps.build.outputs.release }}-linux-amd64.jar
          asset_content_type: application/java-archive
        continue-on-error: true


      - name: Upload Shadow Jar (Linux-Amd64)
        id: upload-shadow-jar-linux-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: build/libs/tigxa-${{ steps.build.outputs.release }}-all.jar
          asset_name: tigxa-${{ steps.build.outputs.release }}-linux-amd64-all.jar
          asset_content_type: application/java-archive
        continue-on-error: true


      - name: Publish to Github Packages
        #run: ./gradlew build
        #working-directory: .
        id: publish
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: publish
        env:
          build_number: ${{ github.run_number }}
          commit_hash: ${{ steps.commithash.outputs.sha_short }}
          gituser: ${{ github.actor }}
          gitpwd: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        
        
        
        
        
        
        
        
        
        
        
        
        
      - name: Build with Gradle (Linux-AArch64)
        #run: ./gradlew build
        #working-directory: .
        id: build-linux-aarch64
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build "-Dos.name=Linux" "-Dos.version=5.13.0-37" "-Dos.arch=aarch64" --refresh-dependencies
        env:
          build_number: ${{ github.run_number }}
          commit_hash: ${{ steps.commithash.outputs.sha_short }}
          gituser: ${{ github.actor }}
          gitpwd: ${{ secrets.GITHUB_TOKEN }}
          os-linux: true
        
      - name: Upload Build Jar (Linux-AArch64)
        id: upload-build-jar-linux-aarch64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: build/libs/tigxa-${{ steps.build.outputs.release }}.jar
          asset_name: tigxa-${{ steps.build.outputs.release }}-linux-aarch64.jar
          asset_content_type: application/java-archive
        continue-on-error: true


      - name: Upload Shadow Jar (Linux-AArch64)
        id: upload-shadow-jar-linux-aarch64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: build/libs/tigxa-${{ steps.build.outputs.release }}-all.jar
          asset_name: tigxa-${{ steps.build.outputs.release }}-linux-aarch64-all.jar
          asset_content_type: application/java-archive
        continue-on-error: true
        
        
        
        
        
        
        
        
        
        
      - name: Build with Gradle (Windows-Amd64)
        #run: ./gradlew build
        #working-directory: .
        id: build-win-amd64
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build "-Dos.name=Windows 11" "-Dos.version=10.0" "-Dos.arch=amd64" --refresh-dependencies
        env:
          build_number: ${{ github.run_number }}
          commit_hash: ${{ steps.commithash.outputs.sha_short }}
          gituser: ${{ github.actor }}
          gitpwd: ${{ secrets.GITHUB_TOKEN }}
          os-linux: true
        
      - name: Upload Build Jar (Windows-Amd64)
        id: upload-build-jar-win-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: build/libs/tigxa-${{ steps.build.outputs.release }}.jar
          asset_name: tigxa-${{ steps.build.outputs.release }}-win-amd64.jar
          asset_content_type: application/java-archive
        continue-on-error: true


      - name: Upload Shadow Jar (Windows-Amd64)
        id: upload-shadow-jar-win-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: build/libs/tigxa-${{ steps.build.outputs.release }}-all.jar
          asset_name: tigxa-${{ steps.build.outputs.release }}-win-amd64-all.jar
          asset_content_type: application/java-archive
        continue-on-error: true
        
        
        
        
        
        
        
        
        
        
      - name: Build with Gradle (Mac-Amd64)
        #run: ./gradlew build
        #working-directory: .
        id: build-mac-amd64
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build "-Dos.name=osx" "-Dos.version=5.13.0-37" "-Dos.arch=amd64" --refresh-dependencies
        env:
          build_number: ${{ github.run_number }}
          commit_hash: ${{ steps.commithash.outputs.sha_short }}
          gituser: ${{ github.actor }}
          gitpwd: ${{ secrets.GITHUB_TOKEN }}
          os-linux: true
        
      - name: Upload Build Jar (Mac-Amd64)
        id: upload-build-jar-mac-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: build/libs/tigxa-${{ steps.build.outputs.release }}.jar
          asset_name: tigxa-${{ steps.build.outputs.release }}-mac-amd64.jar
          asset_content_type: application/java-archive
        continue-on-error: true


      - name: Upload Shadow Jar (Mac-Amd64)
        id: upload-shadow-jar-mac-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: build/libs/tigxa-${{ steps.build.outputs.release }}-all.jar
          asset_name: tigxa-${{ steps.build.outputs.release }}-mac-amd64-all.jar
          asset_content_type: application/java-archive
        continue-on-error: true


      - name: Build with Gradle (Mac-AArch64)
        #run: ./gradlew build
        #working-directory: .
        id: build-mac-aarch64
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build "-Dos.name=osx" "-Dos.version=5.13.0-37" "-Dos.arch=aarch64" --refresh-dependencies
        env:
          build_number: ${{ github.run_number }}
          commit_hash: ${{ steps.commithash.outputs.sha_short }}
          gituser: ${{ github.actor }}
          gitpwd: ${{ secrets.GITHUB_TOKEN }}
          os-linux: true
        
      - name: Upload Build Jar (Mac-AArch64)
        id: upload-build-jar-mac-aarch64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: build/libs/tigxa-${{ steps.build.outputs.release }}.jar
          asset_name: tigxa-${{ steps.build.outputs.release }}-mac-aarch64.jar
          asset_content_type: application/java-archive
        continue-on-error: true


      - name: Upload Shadow Jar (Mac-AArch64)
        id: upload-shadow-jar-mac-aarch64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: build/libs/tigxa-${{ steps.build.outputs.release }}-all.jar
          asset_name: tigxa-${{ steps.build.outputs.release }}-mac-aarch64-all.jar
          asset_content_type: application/java-archive
        continue-on-error: true
