# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Easter-Egg found ... (by MarkusTieger)

name: Gradle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:

  prepare:
    runs-on: ubuntu-latest
    outputs:
      BUILD_ID: ${{ steps.buildnumber.outputs.build_number }}
    steps:
    #- uses: actions/checkout@v2
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{ secrets.github_token }}

  build:

    runs-on: ubuntu-latest
    outputs:
      RELEASE_ID: ${{ steps.build.outputs.release }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      #run: ./gradlew build
      #working-directory: .
      id: build
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: tigxa-1.0.0
        path: build/libs
    - name: Pipe files to release
      uses: KotwOSS/pipe-to-release@<version>
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

        filemap: |
          build/libs/tigxa-${{ needs.build.outputs.RELEASE_ID }}.jar
          build/libs/tigxa-${{ needs.build.outputs.RELEASE_ID }}-all.jar

        skip_errors: true

        release_id: ${{ needs.prepare.outputs.RELEASE_ID }}-${{ needs.prepare.outputs.BUILD_ID }}
